# Generated by Django 4.1.1 on 2022-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_date_alter_post_id_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, related_name='comments', to='app.utilizador'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='app.utilizador'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
