# Generated by Django 4.1.1 on 2022-11-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_likes_count_alter_post_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
