# Generated by Django 4.1.1 on 2022-11-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='bio',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
