# Generated by Django 4.1.3 on 2022-11-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
