# Generated by Django 4.1.3 on 2022-11-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
