# Generated by Django 4.1.1 on 2022-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilizador",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="utilizador",
            name="following",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="followers", to="app.utilizador"
            ),
        ),
        migrations.AlterField(
            model_name="utilizador",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="profile_pics"
            ),
        ),
        migrations.DeleteModel(
            name="Like",
        ),
    ]
