# Generated by Django 4.1.3 on 2022-11-14 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_utilizador_following_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='following',
        ),
        migrations.RemoveField(
            model_name='utilizador',
            name='following_count',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='app.utilizador')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app.utilizador')),
            ],
        ),
    ]
